#!/usr/bin/env bash

# pre-requisites
# https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/steps-overview.html
# 1. Install the Node Feature Discovery operator
# 2. Install the NVIDIA GPU Operator
echo "" && echo "" && echo "Don't forget to install the NVIDIA GPU OPERATOR!!!" && echo "https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/steps-overview.html" && echo "" && echo ""

# Function: print usage and exit
usage_and_exit () {
    echo
    echo $1
    echo
    echo "Usage: setup <project_name>"
    echo
    echo "Example: setup eyelevel"
    echo
    exit 1
}

# Function: error, print usage and exit
error_and_exit () {
    echo
    echo "Review above logs, resolve and try again."
    echo
    echo "To clean up for another attempt, use:"
    echo
    if [ -n "${1:-}" ]; then
        echo "oc delete project $1"
    else
        echo "oc delete project <project_name>"
    fi
    echo
    exit 1
}

# Validate a project name, and only that, is included
if [ $# -lt 1 ]; then
    usage_and_exit "Must include project to deploy to"
elif [ $# -gt 1 ]; then
    usage_and_exit "Too many arguments"
fi

project=$1

# Create the project if it doesn't already exist
oc get project $project > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "$project project already exists. Switching to it."
    oc project $project
else
    echo "Creating new project $project and switching to it."
    oc new-project $project
fi
echo

# Error function on ERR signal
set -euo pipefail  # Exit on error, unset vars, and fail pipelines
trap 'error_and_exit "$project"' ERR

# install the groundx helm chart repo
helm repo add groundx https://registry.groundx.ai/helm --force-update

# install service dependency repos
helm repo add percona https://percona.github.io/percona-helm-charts/ --force-update
helm repo add minio-operator https://operator.min.io/ --force-update

helm repo update

# add node labels to workers
# the groundx pods use these labels with node selectors
echo ""
oc label node -l node-role.kubernetes.io/worker node=eyelevel-node
echo ""
oc get nodes -L node
echo ""

# create a default PV class for namespace
helm upgrade --install groundx-storageclass \
  groundx/groundx-storageclass \
  -n $project

sleep 5

# install Percona MySQL
helm upgrade --install db-operator \
  percona/pxc-operator \
  -n $project \
  -f values/values.percona.operator.yaml

sleep 30

helm upgrade --install db-cluster \
  percona/pxc-db \
  -n $project \
  -f values/values.percona.cluster.yaml

sleep 30

# install MinIO
oc adm policy add-scc-to-user anyuid -z minio-operator -n $project
oc adm policy add-scc-to-user anyuid -z minio-tenant-sa -n $project

helm upgrade --install minio-operator \
  minio-operator/operator \
  -n $project \
  -f values/values.minio.operator.yaml

sleep 30

helm upgrade --install minio-cluster \
  minio-operator/tenant \
  -n $project \
  -f values/values.minio.tenant.yaml

sleep 30

# install Strimzi Kafka
helm upgrade --install stream-operator \
  oci://quay.io/strimzi-helm/strimzi-kafka-operator \
  -n $project \
  -f values/values.strimzi.operator.yaml

sleep 30

helm upgrade --install stream-cluster \
  groundx/groundx-strimzi-kafka-cluster \
  -n $project \
  -f values/values.strimzi.cluster.yaml

sleep 30

# install GroundX secret
helm upgrade --install groundx-secret \
  groundx/groundx-secret \
  -n $project \
  -f values/values.groundx.secret.yaml

sleep 5

# expose minio as a route
oc expose svc/minio -n $project

sleep 5

# install GroundX
helm upgrade --install groundx \
  groundx/groundx \
  -n $project \
  -f values/values.groundx.yaml
