#!/usr/bin/env bash

# pre-requisites
# https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/steps-overview.html
# 1. Install the Node Feature Discovery operator
# 2. Install the NVIDIA GPU Operator

echo "" && echo "" && echo "Don't forget to install the NVIDIA GPU OPERATOR!!!" && echo "https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/steps-overview.html" && echo "" && echo ""

# install the groundx helm chart repo
helm repo add groundx https://registry.groundx.ai/helm

# install service dependency repos
helm repo add percona https://percona.github.io/percona-helm-charts/
helm repo add minio-operator https://operator.min.io/

helm repo update

# add node labels to workers
# the groundx pods use these labels with node selectors
echo ""
oc label node -l node-role.kubernetes.io/worker node=eyelevel-node
echo ""
oc get nodes -L node
echo ""

# create the eyelevel namespace
oc new-project eyelevel
oc project eyelevel

# create a default PV class for namespace
helm upgrade --install groundx-storageclass \
  groundx/groundx-storageclass \
  -n eyelevel

# install Percona MySQL
helm upgrade --install db-operator \
  percona/pxc-operator \
  -n eyelevel \
  -f values/values.percona.operator.yaml

helm upgrade --install db-cluster \
  percona/pxc-db \
  -n eyelevel \
  -f values/values.percona.cluster.yaml

# install MinIO
oc adm policy add-scc-to-user anyuid -z minio-operator -n eyelevel
oc adm policy add-scc-to-user anyuid -z minio-tenant-sa -n eyelevel

helm upgrade --install minio-operator \
  minio-operator/operator \
  -n eyelevel \
  -f values/values.minio.operator.yaml

helm upgrade --install minio-cluster \
  minio-operator/tenant \
  -n eyelevel \
  -f values/values.minio.tenant.yaml

# install Strimzi Kafka
helm upgrade --install stream-operator \
  oci://quay.io/strimzi-helm/strimzi-kafka-operator \
  -n eyelevel \
  -f values/values.strimzi.operator.yaml

helm upgrade --install stream-cluster \
  groundx/groundx-strimzi-kafka-cluster \
  -n eyelevel \
  -f values/values.strimzi.cluster.yaml

# install GroundX secret
helm upgrade --install groundx-secret \
  groundx/groundx-secret \
  -n eyelevel \
  -f values/values.groundx.secret.yaml

# expose minio as a route
oc expose svc/minio -n eyelevel

# install GroundX
helm upgrade --install groundx \
  groundx/groundx \
  -n eyelevel \
  -f values/values.groundx.yaml
